### ISSUE TITLE
Installation failed.

### ISSUE THREAD

**Issue by tobyapi** [funk-yourself/crystal-di#1]
I added this to my shards.yml
```yml
dependencies:
  di:
    github: funk-yourself/crystal-di
```

and run ```crystal deps```, but I encountered following error:
```
Updating https://github.com/funk-yourself/crystal-di.git
git command failed: git ls-tree -r --full-tree --name-only v0.1.0 -- shard.yml (). Maybe a commit, branch or file doesn't exist?
```

```git version 2.14.1```
```Crystal 0.23.1```
